OWASP_TOP10_SCENARIOS = [
    {
        "id": "a01",
        "code": "A01:2025",
        "title": "Broken Access Control",
        "summary": "사용자 권한 경계가 무너질 때 발생하는 문제를 점검한다.",
        "service_case": "일반 사용자가 관리자 페이지나 타인 리소스에 접근 가능한지 확인",
        "checkpoints": [
            "비로그인 사용자의 보호 페이지 접근 차단",
            "일반 사용자의 /admin 접근 차단",
            "타인 게시물/민원 수정 및 조회 차단 (IDOR)",
            "URL 직접 입력을 통한 권한 우회 차단",
        ],
        "mitigations": [
            "모든 수정/삭제 라우트에 서버 측 권한 검증 적용",
            "리소스 소유권 체크와 역할(role) 체크를 분리해 적용",
            "권한 실패를 감사 로그로 기록",
            "기본 거부(deny by default) 정책 적용",
        ],
    },
    {
        "id": "a02",
        "code": "A02:2025",
        "title": "Security Misconfiguration",
        "summary": "잘못된 기본 설정과 운영 설정 누락을 점검한다.",
        "service_case": "디버그 설정, 기본 계정, 과도한 에러 메시지 노출 여부 점검",
        "checkpoints": [
            "프로덕션 환경에서 디버그 모드 비활성화",
            "기본 관리자 계정(admin/admin1234) 변경 여부",
            "에러 페이지에서 스택트레이스 노출 여부",
            "불필요한 HTTP 헤더(Server, X-Powered-By) 제거",
            "디렉토리 리스팅 비활성화",
        ],
        "mitigations": [
            "환경별 설정 분리 (development/production)",
            "초기 계정 비밀번호 강제 변경 절차",
            "표준화된 에러 페이지 사용",
            "보안 헤더 및 프록시 설정 강화",
            "정기적인 설정 감사 수행",
        ],
    },
    {
        "id": "a03",
        "code": "A03:2025",
        "title": "Software Supply Chain Failures",
        "summary": "소프트웨어 공급망의 취약점과 무결성 문제를 점검한다.",
        "service_case": "의존성 버전 관리, 취약한 패키지 사용, CI/CD 보안 점검",
        "checkpoints": [
            "requirements.txt에 버전 고정 여부",
            "알려진 취약점이 있는 패키지 사용 여부 (pip-audit, safety)",
            "의존성 트리의 간접 의존성 파악",
            "SBOM(Software Bill of Materials) 관리 여부",
            "CI/CD 파이프라인 접근 제어 및 로깅",
            "Docker 베이스 이미지 취약점 스캔",
        ],
        "mitigations": [
            "의존성 취약점 스캔 자동화 (Dependabot, Snyk)",
            "SBOM 중앙 관리 및 정기 업데이트",
            "신뢰할 수 있는 공식 소스에서만 패키지 다운로드",
            "빌드 아티팩트 서명 및 검증",
            "분기별 의존성 업그레이드 정책",
            "CI/CD 파이프라인 MFA 및 최소 권한 적용",
        ],
    },
    {
        "id": "a04",
        "code": "A04:2025",
        "title": "Cryptographic Failures",
        "summary": "암호화 및 비밀값 관리 부실로 데이터가 노출될 가능성을 점검한다.",
        "service_case": "시크릿/DB 비밀번호 하드코딩, 평문 민감정보 노출 여부 점검",
        "checkpoints": [
            "SECRET_KEY/DB 비밀번호를 환경변수로 주입하는지 확인",
            "비밀번호 해시 저장 여부 (평문 저장 금지)",
            "민감 데이터 로그 출력 여부 점검",
            "HTTPS 적용 여부 (전송 중 암호화)",
            "약한 암호화 알고리즘 사용 여부",
        ],
        "mitigations": [
            "시크릿 관리 도구 또는 배포 환경 변수 사용",
            "비밀번호는 강력한 해시 알고리즘 사용 (bcrypt, argon2)",
            "민감 필드 마스킹 로깅 적용",
            "TLS 1.2 이상 강제 적용",
            "정기적인 시크릿 로테이션",
        ],
    },
    {
        "id": "a05",
        "code": "A05:2025",
        "title": "Injection",
        "summary": "SQL/명령/템플릿 인젝션 가능 지점을 식별한다.",
        "service_case": "검색·필터 파라미터가 쿼리에 안전하게 전달되는지 검증",
        "checkpoints": [
            "ORM 파라미터 바인딩 사용 여부",
            "동적 문자열 결합 쿼리 사용 금지",
            "입력값 길이·형식 검증 적용",
            "템플릿 인젝션 방어 (Jinja2 autoescaping)",
            "OS 명령 실행 시 입력값 검증",
        ],
        "mitigations": [
            "파라미터화된 쿼리 사용 (ORM 권장)",
            "입력 검증 레이어 공통화",
            "위험 문자열 탐지 로그 추가",
            "출력 인코딩 적용",
            "최소 권한 DB 계정 사용",
        ],
    },
    {
        "id": "a06",
        "code": "A06:2025",
        "title": "Insecure Design",
        "summary": "설계 단계에서의 보안 요구 누락을 식별한다.",
        "service_case": "민원 처리 흐름에 승인·검증 단계가 빠져 있는지 점검",
        "checkpoints": [
            "관리자 전용 프로세스의 다단계 검증 여부",
            "비정상 흐름(직접 URL 접근) 처리 여부",
            "오류/예외 플로우에서 정보 노출 여부",
            "Rate limiting 적용 여부",
            "업무 규칙 기반 상태 전이 검증",
        ],
        "mitigations": [
            "위협 모델링 기반 설계 리뷰",
            "업무 규칙 기반 상태 전이 정의",
            "권한/상태 전이 테스트 케이스 유지",
            "Rate limiting 및 throttling 적용",
            "보안 요구사항을 설계 문서에 명시",
        ],
    },
    {
        "id": "a07",
        "code": "A07:2025",
        "title": "Authentication Failures",
        "summary": "인증 절차와 세션 관리 취약점을 점검한다.",
        "service_case": "약한 비밀번호 정책, 세션 보호 설정, 로그인 시도 제한 점검",
        "checkpoints": [
            "비밀번호 최소 길이 및 복잡도 검증",
            "로그인 실패 누적 제한(계정 잠금/지연) 여부",
            "세션 쿠키 보호 플래그 (HttpOnly, Secure, SameSite)",
            "세션 고정 공격 방어",
            "비밀번호 재설정 프로세스 보안",
        ],
        "mitigations": [
            "계정 잠금/지연 정책 적용",
            "MFA(다중 인증) 도입",
            "세션 보안 설정 강화",
            "로그인 성공/실패 로깅",
            "비밀번호 정책 강화 (NIST 800-63b 참고)",
        ],
    },
    {
        "id": "a08",
        "code": "A08:2025",
        "title": "Software or Data Integrity Failures",
        "summary": "코드/데이터 무결성 검증 부족을 점검한다.",
        "service_case": "배포 아티팩트, 의존성, 시드 데이터 변경 이력 추적",
        "checkpoints": [
            "배포 단위 체크섬/서명 사용 여부",
            "중요 설정 파일 변경 이력 검토",
            "신뢰되지 않은 원본 코드 반영 금지",
            "자동 업데이트 무결성 검증",
            "역직렬화 입력 검증",
        ],
        "mitigations": [
            "CI에서 아티팩트 검증",
            "릴리스 승인 프로세스",
            "변경 이력 감사 강화",
            "코드 리뷰 필수화",
            "서명된 커밋 사용",
        ],
    },
    {
        "id": "a09",
        "code": "A09:2025",
        "title": "Security Logging and Alerting Failures",
        "summary": "탐지, 추적, 알림이 가능한 로그 체계를 점검한다.",
        "service_case": "로그인/권한변경/민원처리 로그의 저장·조회·알림 가능 여부 확인",
        "checkpoints": [
            "핵심 액션 감사로그 기록 (로그인, 권한변경, 데이터 변경)",
            "오류 발생 시 로깅 및 알림 체계",
            "로그 보존 기간 정책",
            "로그 무결성 보호 (변조 방지)",
            "실시간 이상 탐지 및 알림 시스템",
            "민감 정보 로깅 방지 (PII 마스킹)",
        ],
        "mitigations": [
            "운영 모니터링 대시보드 연결",
            "이상 징후 알림 (Slack, 이메일 등 연계)",
            "로그 무결성 보장 (WORM 스토리지)",
            "NIST 800-61r2 기반 사고 대응 계획",
            "정기적인 로그 리뷰 프로세스",
        ],
    },
    {
        "id": "a10",
        "code": "A10:2025",
        "title": "Mishandling of Exceptional Conditions",
        "summary": "비정상 상황에서의 부적절한 예외 처리를 점검한다.",
        "service_case": "에러 발생 시 민감 정보 노출, Fail Open 동작, 리소스 고갈 대응 점검",
        "checkpoints": [
            "예외 발생 시 스택트레이스/민감정보 노출 여부 (CWE-209)",
            "인증/인가 실패 시 Fail Open 동작 여부 (CWE-636)",
            "NULL/빈 값 입력 시 적절한 처리 여부",
            "리소스 고갈(메모리, 연결) 시 서비스 동작",
            "타임아웃 설정 및 처리",
            "에러 복구 후 일관된 상태 유지",
        ],
        "mitigations": [
            "표준화된 에러 핸들러 사용 (사용자에게 상세 정보 미노출)",
            "Fail Closed 원칙 적용 (실패 시 거부)",
            "모든 입력에 대한 경계 조건 테스트",
            "리소스 제한 (Rate limiting, 메모리 제한)",
            "트랜잭션 롤백 및 정리 로직 구현",
            "예외 상황 모니터링 및 알림",
        ],
    },
]
